source:
  host: 192.168.109.12
  port: 5432
  username: openerp
  password: A6eC9qf0AenECZdh
  database: Portal_prod
  batch: 10000
destination:
  ssh:
    host: 52.60.113.32
    user: ubuntu
    pkey: /conf/delmar_aws_key.pem
  db:
    user: odoo
    password: odoo
    database: delmar-final-import-test
    schema: public
